---
### Drone configuration file for gotosocial-drone-build
### Connects to https://drone.superseriousbusiness.org to perform testing, linting, and automatic builds/pushes to docker.
###
### For documentation on drone, see: https://docs.drone.io/
### For documentation on drone docker pipelines in particular: https://docs.drone.io/pipeline/docker/overview/

kind: pipeline
type: docker
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    username: gotosocial
    password:
      from_secret: gts_docker_password
    repo: superseriousbusiness/gotosocial-drone-build
    tags:
    - latest 
    - "0.0.5"
    build_args:
    - GORELEASER_VERSION=v1.9.2
    - GO_SWAGGER_VERSION=v0.29.0
    - DOCKER_BUILDX_VERSION=v0.8.2
    - GO_CONTAINER_VERSION=1.18.3-alpine
  when:
    event:
      include:
      - push
    branch:
      include:
      - main

trigger:
  repo:
    exclude:
    - "*"
    include:
    - superseriousbusiness/gotosocial-drone-build

---
kind: signature
hmac: 7335d5f7c880c8f396717f57790257bb2bf3fb4221dbe8d1ec1d33ce378c56b4

...
